### PR TITLE
OZ-49: Adding jsonkeyvalues to activate Data Extracts reports.

### PR DESCRIPTION
**Pull request by Ruhanga**
Ticket: https://mekomsolutions.atlassian.net/browse/OZ-49
Related PR: https://github.com/ozone-his/ozone-distro/pull/7

### CODE REVIEW

**Review by mks-d — CHANGES_REQUESTED** [review]
@Ruhanga the data extract reports should be activated by default as a "core feature" of Common Reports. At that point this PR will not be necessary anymore.

**Comment by Ruhanga** [comment]
There could be those running MSPP reports for example and don't want to deactivate what they don't need. Would this not affect them?

**Comment by mks-d** [comment]
General purpose reports, such as the data extracts, can just be available for anyone to use. This is also the case with the patient history if I remember well.

**Comment by Ruhanga** [comment]
Closing this in favour of [this PR](https://github.com/mekomsolutions/openmrs-module-commonreports/pull/57) on common reports.

**Pull request closed without merging**
